#!/usr/bin/env zsh
# Build the single-file bundle — the whole library concatenated into one distributable
# `.zsh-theme`, in dependency order, from the explicit manifest below.
#
# The manifest is spelled out rather than derived because the order is a contract, and a
# contract is written down. But it is a TRANSCRIPTION of the entry point's source list — the
# one place that order is decided — so before anything is emitted the two are compared, and a
# mismatch is a build failure rather than a bundle that loads in the wrong order. The install
# calls at the tail are taken from the entry point verbatim for the same reason: one source of
# truth, checked, not copied on faith.
#
# Usage: zsh -f tools/bundle.zsh [output-file]     (default: dist/inzsh.zsh-theme)
#
# One more thing the head carries that is not a transcription: `_inzsh_version`. The entry
# point's own copy of that line always reads `source` — issue #244's single-source constant, and
# a checkout has no tag to read without a subprocess, so it says so rather than guessing. This is
# the one place it is ever allowed to say something else, and it does so from the environment
# rather than a number written here: `INZSH_BUNDLE_VERSION`, set by the release workflow's
# `prepare` step to the exact tag semantic-release just decided (see docs/releasing.md), unset
# everywhere else so a local `make bundle` still honestly says `source`.
emulate -L zsh
setopt err_exit no_unset pipe_fail extended_glob

typeset -g _inzsh_bundle_root=${${(%):-%x}:A:h:h}
typeset -g _inzsh_bundle_entry=$_inzsh_bundle_root/inzsh.zsh-theme
typeset -g _inzsh_bundle_out=${1:-$_inzsh_bundle_root/dist/inzsh.zsh-theme}

# The manifest. Dependency order, strictly downward — config → detect → tokens → layout →
# engine → render/prompts/transient/resize/hooks — then the salah library (a sibling leaf,
# calc → methods → cache → location), then the segments in registration order.
typeset -ga _inzsh_bundle_manifest=(
  lib/core/config.zsh
  lib/core/detect.zsh
  lib/core/tokens-256.zsh
  lib/core/tokens.zsh
  lib/core/layout.zsh
  lib/core/engine.zsh
  lib/core/render.zsh
  lib/core/prompts.zsh
  lib/core/transient.zsh
  lib/core/resize.zsh
  lib/core/hooks.zsh
  lib/core/doctor.zsh
  lib/salah/calc.zsh
  lib/salah/methods.zsh
  lib/salah/cache.zsh
  lib/salah/location.zsh
  lib/segments/root.zsh
  lib/segments/user.zsh
  lib/segments/host.zsh
  lib/segments/ssh.zsh
  lib/segments/dir.zsh
  lib/segments/venv.zsh
  lib/segments/git.zsh
  lib/segments/git-async.zsh
  lib/segments/retval.zsh
  lib/segments/duration.zsh
  lib/segments/jobs.zsh
  lib/segments/time.zsh
  lib/segments/date.zsh
  lib/segments/salah.zsh
)

# Hold the transcription to its source. The entry point's `source` lines are the decided
# order; the install calls at its tail are the decided close. Read both, and refuse to build
# from a manifest that has drifted.
typeset -ga _inzsh_bundle_entry_list=() _inzsh_bundle_installs=()
typeset _inzsh_bundle_line
while IFS= read -r _inzsh_bundle_line; do
  if [[ $_inzsh_bundle_line == source*_inzsh_theme_root/lib/* ]]; then
    _inzsh_bundle_entry_list+=("${_inzsh_bundle_line##*_inzsh_theme_root/}")
  elif [[ $_inzsh_bundle_line == _inzsh_[a-z_]## ]]; then
    _inzsh_bundle_installs+=("$_inzsh_bundle_line")
  fi
done < $_inzsh_bundle_entry

if [[ "${(j:|:)_inzsh_bundle_entry_list}" != "${(j:|:)_inzsh_bundle_manifest}" ]]; then
  print -ru2 -- 'bundle: the manifest no longer matches the entry point — the order is decided'
  print -ru2 -- 'there, so fix the manifest in tools/bundle.zsh to match:'
  print -ru2 -- "  entry point: ${_inzsh_bundle_entry_list[*]}"
  print -ru2 -- "  manifest:    ${_inzsh_bundle_manifest[*]}"
  exit 1
fi

typeset _inzsh_bundle_file
for _inzsh_bundle_file in $_inzsh_bundle_manifest; do
  if [[ ! -f $_inzsh_bundle_root/$_inzsh_bundle_file ]]; then
    print -ru2 -- "bundle: manifest names a file that does not exist: $_inzsh_bundle_file"
    exit 1
  fi
done

mkdir -p -- ${_inzsh_bundle_out:h}

# Emit. The head is the entry point's own head — the guard first, above everything, for the
# reason the entry point gives — then each manifest file under a marker naming its source
# path, then the entry point's tail verbatim.
{
  print -r -- '# InZsh — single-file bundle. Generated by tools/bundle.zsh; do not edit.'
  print -r -- '# Source this file from .zshrc, or drop it into an oh-my-zsh themes directory.'
  print -r -- '[[ -o interactive ]] || return 0'
  print -r -- 'typeset -g _inzsh_theme_root=${${(%):-%x}:A:h}'
  print -r -- "typeset -g _inzsh_version=${(qq)${INZSH_BUNDLE_VERSION:-source}}"
  for _inzsh_bundle_file in $_inzsh_bundle_manifest; do
    print -r -- ''
    print -r -- "# ── $_inzsh_bundle_file ──"
    cat -- $_inzsh_bundle_root/$_inzsh_bundle_file
  done
  print -r -- ''
  print -r -- '# ── close — the entry point tail ──'
  print -rl -- $_inzsh_bundle_installs
} > $_inzsh_bundle_out

print -r -- "bundle: ${#_inzsh_bundle_manifest} files → ${_inzsh_bundle_out#$_inzsh_bundle_root/}"
